"use client";
import { useLedgerTimeZone } from "./ledger-clock";
import { ledgerToday } from "@/lib/domain/ledger-time";
import CorrectionModal, {type CorrectionTarget} from "./correction-modal";
import { useState } from 'react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import { ledgerEventFromRow } from '@/lib/domain/ledger-adapter';
import { buildInvestmentSnapshot, investmentAllocation, positionReturn, valuationDue } from '@/lib/domain/investment-snapshot';
import type { InvestmentSnapshot } from './app-client';
import type { FxRateSnapshot } from '@/lib/domain/fx-rates';
import { InvestmentMetadataModal } from './investment-modal';
type Row=Record<string,unknown>;
const money=(n:number,c:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(n/100);
const colors=['#1f5243','#b67b48','#668d9d','#aea16c','#8584a0','#6e9a72'];
export default function InvestmentCenter({householdId,investments,valuations,entries,currency,openCreate,openAction,snapshots,fxSnapshot,archived=false,readOnly=false,refresh=()=>undefined,notify=()=>undefined}: {householdId?:string;investments:Row[];valuations:Row[];entries:Row[];currency:string;openCreate:()=>void;openAction:(id:string)=>void;snapshots?:Record<string,InvestmentSnapshot>;fxSnapshot?:FxRateSnapshot;archived?:boolean;readOnly?:boolean;refresh?:()=>void;notify?:(s:string)=>void}) {
 const timeZone = useLedgerTimeZone();
 const [grouping,setGrouping]=useState<'instrument'|'asset'>('instrument'),[editing,setEditing]=useState<Row|null>(null);
 const [correction,setCorrection]=useState<CorrectionTarget>();
 const views: {investment:Row;snapshot:InvestmentSnapshot}[]=investments.map(i=>{try{return {investment:i,snapshot:snapshots?.[String(i.id)]??buildInvestmentSnapshot(entries.map(ledgerEventFromRow),i,valuations)};}catch(e){return {investment:i,snapshot:{error:e instanceof Error?e.message:'投资数据待核对'} as InvestmentSnapshot};}});
 let allocation:ReturnType<typeof investmentAllocation>|undefined,allocationError='',overallReturn='待估值';
 try{
  if(views.some(v=>v.snapshot.error)) throw new Error('存在待核对的标的，完整配置暂不可计算');
  allocation=investmentAllocation(views.filter(v=>v.snapshot.position?.quantityMilli).map(v=>({id:String(v.investment.id),name:String(v.investment.name),assetType:String(v.investment.asset_type??"其他"),currency:String(v.investment.currency),marketMinor:v.snapshot.valuation!.marketMinor,estimated:v.snapshot.valuation!.source==='cost_estimate'})),currency,fxSnapshot,grouping);
  if(allocation.rows.length&&!allocation.estimated){const cost=investmentAllocation(views.filter(v=>v.snapshot.position?.quantityMilli).map(v=>({id:String(v.investment.id),name:String(v.investment.name),assetType:String(v.investment.asset_type??'其他'),currency:String(v.investment.currency),marketMinor:v.snapshot.position!.remainingCostMinor,estimated:false})),currency,fxSnapshot);overallReturn=cost.total?`${allocation.total>=cost.total?'+':''}${((allocation.total-cost.total)/cost.total*100).toFixed(2)}%`:'无成本基数';}
 }catch(e){allocationError=e instanceof Error?e.message:'配置待核对';}
 return <div className="space-y-4">{correction&&<CorrectionModal target={correction} householdId={householdId??""} snapshot={fxSnapshot} close={()=>setCorrection(undefined)} refresh={refresh} notify={notify} readOnly={readOnly}/>}<div className="flex flex-wrap justify-between gap-3 rounded-2xl bg-[#edf7ed] p-5"><div><b>投资台账</b><p className="mt-1 text-sm text-gray-500">各标的独立提交投资操作，由另一位成员审批。银行转入与买入可一次确认。</p></div><button disabled={archived} onClick={openCreate} className="rounded-xl bg-[#1f5243] px-4 py-2 text-sm font-bold text-white">新增投资标的</button></div>
 <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">投资配置</h2><select aria-label="配置分组" value={grouping} onChange={e=>setGrouping(e.target.value as 'instrument'|'asset')} className="rounded-lg border p-2"><option value="instrument">按标的</option><option value="asset">按资产类型</option></select></div><p className="mt-2 text-xs text-gray-500">仅含投资持仓；共同银行、券商闲置现金和成员欠款不计入。{fxSnapshot?`统一采用 ${fxSnapshot.effectiveAt.slice(0,10)} 的已批准汇率。`:'跨币种配置需要已批准汇率。'}</p>
 {allocationError?<p className="mt-4 text-red-700">{allocationError}</p>:!allocation?.rows.length?<p className="mt-4 text-gray-500">当前投资总市值为零，暂无配置比例。</p>:<><p className="mt-3 font-bold">总市值 {money(allocation.total,currency)} · 整体持仓涨跌幅 {overallReturn}{allocation.estimated?' · 含成本暂估':''}</p><div className="grid gap-4 md:grid-cols-[280px_1fr]"><div className="h-64" role="img" aria-label="投资配置环图"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={allocation.rows} dataKey="rawMinor" nameKey="name" innerRadius={65} outerRadius={100} isAnimationActive={false}>{allocation.rows.map((r,index)=><Cell key={r.id} fill={colors[index%colors.length]}/>)}</Pie><Tooltip formatter={value=>money(Number(value),currency)}/></PieChart></ResponsiveContainer></div><div className="overflow-x-auto"><table className="mt-4 w-full text-left text-sm"><thead><tr><th>配置</th><th>市值（{currency}）</th><th>占比</th><th>来源</th></tr></thead><tbody>{allocation.rows.map((r,index)=><tr key={r.id} className="border-t"><td className="py-3"><span style={{color:colors[index%colors.length]}}>● </span>{r.name}</td><td>{money(r.minor,currency)}</td><td>{(r.percentHundredths/100).toFixed(2)}%</td><td>{r.estimated?'含成本暂估':'人工估值'}</td></tr>)}</tbody></table></div></div></>}
 <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-xs"><caption className="mb-3 text-left font-bold">持仓估值明细（原币涨跌幅）</caption><thead><tr><th>标的</th><th>原币市值</th><th>剩余成本</th><th>持仓涨跌幅</th><th>估值来源 / 日期</th></tr></thead><tbody>{views.filter(v=>v.snapshot.position?.quantityMilli).map(({investment:i,snapshot:s})=>{const result=positionReturn(s.position!,s.valuation!);return <tr key={String(i.id)} className="border-t"><td className="py-3">{String(i.name)}</td><td>{String(i.currency)} {money(s.valuation!.marketMinor,String(i.currency))}</td><td>{money(s.position!.remainingCostMinor,String(i.currency))}</td><td>{result.percent==null?result.label:`${result.percent>=0?'+':''}${result.percent.toFixed(2)}%`}</td><td>{s.valuation!.source==='cost_estimate'?'成本暂估':`人工估值 / ${s.latestValueDate}`}</td></tr>;})}</tbody></table></div>
 </section>
 {views.map(({investment:i,snapshot:s})=>{const id=String(i.id),c=String(i.currency),records=entries.filter(e=>e.investment_id===id),result=s.position&&s.valuation?positionReturn(s.position,s.valuation):undefined;return <article key={id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{String(i.name)}</h2><p className="mt-1 text-xs text-gray-500">{String(i.ticker??'')} · {String(i.asset_type??"其他")} · {c}{s.position?` · 可卖 ${s.position.quantityMilli/1000} ${String(i.unit_name??'份')}`:''}</p>{Boolean(i.note)&&<p className="mt-1 text-xs text-gray-500">{String(i.note)}</p>}</div><div className="flex gap-2"><button disabled={archived} onClick={()=>setEditing(i)} className="rounded-xl border px-3 py-2 text-sm">编辑标的</button><button disabled={archived} onClick={()=>openAction(id)} className="rounded-xl border border-[#1f5243] px-3 py-2 text-sm font-bold text-[#1f5243]">投资操作</button></div></div>
 {s.error?<p className="mt-4 text-red-700">{s.error}</p>:s.position&&s.valuation&&<><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3">{[[s.valuation.source==='cost_estimate'?'当前市值（成本暂估）':'当前市值',money(s.valuation.marketMinor,c)],['剩余成本',money(s.position.remainingCostMinor,c)],['未实现收益',s.valuation.unrealizedGainMinor===null?'待估值':money(s.valuation.unrealizedGainMinor,c)],['已实现收益',money(s.position.realizedGainMinor,c)],['累计分红',money(s.position.dividendMinor,c)]].map(([label,value])=><div key={label} className="rounded-xl bg-[#f6f6f2] p-3"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}<div className="rounded-xl bg-[#f6f6f2] p-3"><p className="text-xs text-gray-500">{result?.label}</p><p className={`mt-1 font-bold ${result?.percent!=null?(result.percent>=0?'text-green-800':'text-red-700'):''}`}>{result?.percent==null?'—':`${result.percent>=0?'+':''}${result.percent.toFixed(2)}%`}</p></div></div><p className="mt-3 text-xs text-gray-500">{s.latestValueDate?`人工估值日期：${s.latestValueDate} · 基于该日价格估算持仓。`:'尚无本轮人工估值；暂按剩余成本展示。'}</p>{!archived&&s.position.quantityMilli>0&&valuationDue(String(i.valuation_cadence??'weekly'),s.latestValueDate,ledgerToday(timeZone))&&<p className="mt-2 text-sm text-amber-800">{i.valuation_cadence==='monthly'?'本月':'本周'}尚未估值，请在投资操作中更新。</p>}</>}
 <div className="mt-4 border-t pt-3 text-sm"><b>最近交易</b>{records.length?records.slice(-8).map(e=><p key={String(e.id)} className="mt-2">{String(e.occurred_at)} · {String(e.entry_type)} · {money(Number(e.amount_minor),c)}</p>):<p className="mt-2 text-gray-500">当前列表页没有该标的交易；持仓仍按完整账本计算。</p>}</div></article>;})}
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">估值审批历史</h2>{valuations.map(v=><div key={String(v.id)} className="mt-3 border-t pt-3 text-sm"><p>{String(investments.find(i=>i.id===v.investment_id)?.name??v.investment_id)} · {String(v.value_date)} · {v.status==="voided"?"已作废":"已确认"}</p><p className="text-xs text-gray-500">估值编号 {String(v.id)}{v.void_proposal_id?` · 作废审批 ${String(v.void_proposal_id)}`:""}</p>{v.status!=="voided"&&householdId&&<button disabled={archived} className="mt-2 underline" onClick={()=>setCorrection({mode:"void",kind:"valuation",entry:v,previewPlan:readOnly?{entries:[],transfers:[],valuations:[v]}:undefined})}>申请作废估值</button>}</div>)}{!valuations.length&&<p className="mt-3 text-sm text-gray-500">暂无人工估值历史。</p>}</section>
 {!investments.length&&<p>尚未有投资标的。创建标的后，可在对应卡片中发起投资操作。</p>}
 {editing&&<InvestmentMetadataModal investment={editing} close={()=>setEditing(null)} householdId={String(editing.household_id??'')} refresh={refresh} notify={notify} readOnly={readOnly}/>}
 </div>;
}
