"use client";
import { useLedgerTimeZone } from "./ledger-clock";
import { ledgerToday } from "@/lib/domain/ledger-time";
import { useEffect, useState } from 'react';
import { parseFixedDecimal } from '@/lib/domain/fixed-decimal';
import { ledgerEventFromRow } from '@/lib/domain/ledger-adapter';
import { investmentBasis } from '@/lib/domain/investment-snapshot';
import { proposalSchema } from '@/lib/validation/proposal';
import type { AccountBalances, CashTransfer } from '@/lib/domain/account-balances';
type Row=Record<string,unknown>;
const emptyRows:Row[]=[];
type Basis={quantityMicro:number;throughSequence:string;revision:number;signature:string};
const money=(n:number,c:string)=>`${c} ${(n/100).toFixed(2)}`;
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-label={title} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6"><div className="mb-4 flex justify-between"><b>{title}</b><button type="button" aria-label="关闭" onClick={close}>×</button></div><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:p-3 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:p-3 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:p-3">{children}</div></div></div>;}
export function InvestmentActionModal({investment,householdId,close,refresh,notify,readOnly=false,entries=emptyRows,transfers=[],balances}: {investment:Row;householdId:string;close:()=>void;refresh:()=>void;notify:(s:string)=>void;readOnly?:boolean;entries?:Row[];transfers?:CashTransfer[];balances?:AccountBalances}) {
 const timeZone=useLedgerTimeZone(); const today=()=>ledgerToday(timeZone);
 const [type,setType]=useState('investment_buy'),[date,setDate]=useState(today()),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[quantity,setQuantity]=useState(''),[price,setPrice]=useState(''),[fundingMode,setFundingMode]=useState('cash'),[fundingCurrency,setFundingCurrency]=useState(String(investment.currency)),[fundingAmount,setFundingAmount]=useState(''),[arrival,setArrival]=useState(''),[transferDate,setTransferDate]=useState(today()),[linkedTransfer,setLinkedTransfer]=useState(''),[valuationMode,setValuationMode]=useState('total_market'),[valuationValue,setValuationValue]=useState(''),[basisState,setBasisState]=useState<{key:string;basis?:Basis;error?:string}>({key:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestKey]=useState(()=>globalThis.crypto.randomUUID());
 const id=String(investment.id),currency=String(investment.currency),basisKey=`${id}:${date}`;
 let previewBasis:Basis|undefined,previewBasisError='';
 if(readOnly&&type==='investment_valuation') {try{const events=entries.map(ledgerEventFromRow),sequence=events.reduce((s,e)=>BigInt(e.effectiveSequence??'0')>BigInt(s)?e.effectiveSequence!:s,'0');previewBasis=investmentBasis(events,id,date,sequence,Number(investment.opening_quantity_milli??0),Number(investment.opening_cost_minor??0));}catch(e){previewBasisError=e instanceof Error?e.message:'基准无效';}}
 const basis=readOnly?previewBasis:basisState.key===basisKey?basisState.basis:undefined;
 useEffect(()=>{
  if(type!=='investment_valuation')return;
  const abort=new AbortController();
  if(readOnly)return;
  fetch(`/api/investments/${id}/basis?date=${date}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error??'无法读取持仓');if(!abort.signal.aborted)setBasisState({key:basisKey,basis:b});}).catch(e=>{if(!abort.signal.aborted)setBasisState({key:basisKey,error:e.message});});
  return()=>abort.abort();
 },[type,id,date,basisKey,readOnly,entries,investment.opening_quantity_milli,investment.opening_cost_minor]);
 const eligibleTransfers=transfers.filter(t=>t.destinationAccountKind==='brokerage'&&(t.destinationCurrency??t.currency)===currency&&Boolean(t.occurredAt)&&t.occurredAt!<=date&&t.status==='posted');
 let preview:Row|undefined;
 try{
  const payload:Row={householdId,idempotencyKey:requestKey,type,currency,occurredAt:date,title:title||`${String(investment.name)} · ${type}`,investmentId:id,amountMinor:type==='investment_valuation'?0:parseFixedDecimal(amount,2,{allowZero:type==='investment_sell',label:'实际金额'})};
  if(type==='investment_buy'||type==='investment_sell'){payload.quantityMicro=parseFixedDecimal(quantity,6,{allowZero:false,label:'份额'});if(price)payload.unitPriceHundredMillionths=parseFixedDecimal(price,8,{allowZero:false,label:'参考单价'});}
  if(type==='investment_buy'&&fundingMode==='bank')payload.funding={currency:fundingCurrency,amountMinor:parseFixedDecimal(fundingAmount,2,{allowZero:false,label:'转出金额'}),destinationAmountMinor:parseFixedDecimal(fundingCurrency===currency?fundingAmount:arrival,2,{allowZero:false,label:'到账金额'}),occurredAt:transferDate};
  if(type==='investment_buy'&&fundingMode==='cash'&&linkedTransfer)payload.linkedTransferId=linkedTransfer;
  if(type==='investment_valuation'){payload.valuationMode=valuationMode;payload.basis=basis;if(valuationMode==='total_market')payload.totalValueMinor=parseFixedDecimal(valuationValue,2,{allowZero:true,label:'总市值'});else payload.unitValueHundredMillionths=parseFixedDecimal(valuationValue,8,{allowZero:true,label:'单位净值'});}
  const parsed=proposalSchema.safeParse(payload);if(parsed.success)preview=parsed.data;
 }catch{/* Incomplete fields are expected while entering values. */}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!preview)return setError('请填写有效金额、份额与日期；估值需要确认非零持仓。');if(readOnly)return notify('只读预览：已展示固定提案内容，不会提交。');setBusy(true);try{const response=await fetch('/api/proposals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(preview)}),body=await response.json();if(!response.ok)throw new Error(body.error??'提交失败');close();notify('投资提案已提交，等待另一位成员审批。');refresh();}catch(e){setError(e instanceof Error?e.message:'提交失败');}finally{setBusy(false);}}
 return <Shell title={`${String(investment.name)} · 投资操作`} close={close}><form onSubmit={submit} className="space-y-3"><p className="text-sm">当前标的：{String(investment.name)} · {currency}</p><p className="text-xs text-gray-500">结算账户：共同券商。金额采用实际总扣款或净到账；参考单价不参与成本核算。</p><label className="block text-sm">投资操作<select aria-label="投资操作类型" value={type} onChange={e=>{setType(e.target.value);setError('');}}><option value="investment_buy">投资买入</option><option value="investment_sell">投资卖出</option><option value="dividend">分红</option><option value="investment_valuation">更新估值</option></select></label><label className="block text-sm">{type==='investment_valuation'?'估值日期':'交易日期'}<input aria-label="交易日期" type="date" max={today()} required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="block text-sm">说明<input aria-label="操作说明" value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} placeholder="可选，自定操作说明"/></label>
 {type==='investment_valuation'?<><label className="block text-sm">估值方式<select aria-label="估值方式" value={valuationMode} onChange={e=>{setValuationMode(e.target.value);setValuationValue('');}}><option value="total_market">当前持仓总市值（默认）</option><option value="unit_price">单位净值 / 单价</option></select></label><p className="rounded-xl bg-[#edf7ed] p-3 text-sm">{basis?`确认基准：${basis.quantityMicro/1e6} ${String(investment.unit_name??'份')} · ${date} · 版本 ${basis.revision}`:previewBasisError?previewBasisError:basisState.key===basisKey&&basisState.error?basisState.error:'正在读取当日已确认持仓…'}</p>{basis&&basis.quantityMicro<=0&&<p className="text-sm text-red-700">该日没有持仓，不能更新估值。</p>}<label className="block text-sm">{valuationMode==='total_market'?`总市值（${currency}，可为 0）`:`单位净值（${currency}，最多 8 位小数，可为 0）`}<input aria-label="估值金额" inputMode="decimal" required value={valuationValue} onChange={e=>setValuationValue(e.target.value)}/></label>{preview&&basis&&valuationMode==='total_market'&&<p className="text-xs text-gray-500">换算单价约 {(Number(preview.totalValueMinor)*10000/basis.quantityMicro).toFixed(8)} {currency}；保存原始总市值 / 份额比值，计算时只在最终金额取整。</p>}<p className="text-xs text-gray-500">提交后若历史依赖变化，将要求撤回并重新确认；普通后续交易按该日价格估算。</p></>:<><label className="block text-sm">{type==='investment_buy'?'实际总扣款':'实际净到账'}（{currency}）<input aria-label="实际金额" required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label>{type!=='dividend'&&<><label className="block text-sm">份额（最多 6 位小数）<input aria-label="份额" required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="block text-sm">参考单价（可选，最多 8 位小数）<input aria-label="参考单价" inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)}/></label></>}
 {type==='investment_buy'&&<><label className="block text-sm">资金方式<select aria-label="资金方式" value={fundingMode} onChange={e=>setFundingMode(e.target.value)}><option value="cash">现有券商现金（默认）</option><option value="bank">银行转入并买入</option></select></label>{fundingMode==='bank'?<div className="space-y-3 rounded-xl border p-3"><label className="block text-sm">转入日期<input aria-label="转入日期" type="date" max={date} required value={transferDate} onChange={e=>setTransferDate(e.target.value)}/></label><label className="block text-sm">银行转出币种<select aria-label="银行转出币种" value={fundingCurrency} onChange={e=>setFundingCurrency(e.target.value)}>{['USD','CNY','HKD'].map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm">银行转出金额<input aria-label="银行转出金额" inputMode="decimal" required value={fundingAmount} onChange={e=>setFundingAmount(e.target.value)}/></label>{fundingCurrency!==currency&&<label className="block text-sm">券商实际到账（{currency}）<input aria-label="券商实际到账" inputMode="decimal" required value={arrival} onChange={e=>setArrival(e.target.value)}/></label>}<p className="text-xs text-gray-500">同币种到账等于转出；跨币种填写实际到账并冻结批准汇率。转入、买入金额彼此独立，余额变化不会调整提案。</p></div>:<label className="block text-sm">关联已生效转入（可选，不再扣款）<select aria-label="关联已生效转入" value={linkedTransfer} onChange={e=>setLinkedTransfer(e.target.value)}><option value="">不关联</option>{eligibleTransfers.map(t=><option key={t.id} value={t.id}>{t.occurredAt} · {money(t.destinationAmountMinor??t.amountMinor,currency)}</option>)}</select></label>}</>}
 </>}
 {preview&&<InvestmentProposalDetails payload={preview}/>}{preview&&balances&&<CashPreview payload={preview} balances={balances}/>} {error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy||!preview} className="w-full rounded-xl bg-[#1f5243] py-3 font-bold text-white disabled:opacity-40">{busy?'提交中…':readOnly?'查看提案（只读）':'提交审批'}</button></form></Shell>;
}
function CashPreview({payload:p,balances}:{payload:Row;balances:AccountBalances}){const c=String(p.currency) as 'USD'|'CNY'|'HKD',f=p.funding as Row|undefined,kind='brokerage';const bank=f?balances.bank[String(f.currency) as typeof c]-Number(f.amountMinor):undefined;const broker=balances[kind][c]+(f?Number(f.destinationAmountMinor):0)+(p.type==='investment_buy'?-Number(p.amountMinor):p.type==='investment_sell'||p.type==='dividend'?Number(p.amountMinor):0);return <p className="text-xs text-gray-500">按当前余额预览：{bank!=null&&f?`银行 ${money(bank,String(f.currency))}；`:''}券商 {money(broker,c)}。批准时按固定增减额记账，可出现负现金。</p>;}
export function InvestmentProposalDetails({payload:p}:{payload:Row}){if(!String(p.type).startsWith('investment_')&&p.type!=='dividend')return null;const f=p.funding as Row|undefined,b=p.basis as Basis|undefined;return <div className="mt-3 space-y-1 rounded-xl bg-[#f3f6ef] p-3 text-xs"><b>固定投资提案</b>{f&&<p>① {String(f.occurredAt)} 银行 -{money(Number(f.amountMinor),String(f.currency))} → 券商 +{money(Number(f.destinationAmountMinor),String(p.currency))}</p>}{p.type!=='investment_valuation'?<p>{f?'② ':''}{String(p.occurredAt)} {p.type==='investment_buy'?'买入 · 券商扣款':p.type==='investment_sell'?'卖出 · 券商净到账':'分红 · 券商净到账'} {money(Number(p.amountMinor),String(p.currency))}{p.quantityMicro!=null?` · ${Number(p.quantityMicro)/1e6} 份`:p.quantityMilli!=null?` · ${Number(p.quantityMilli)/1000} 份`:''}</p>:<p>{String(p.occurredAt)} {p.valuationMode==='total_market'?`总市值 ${money(Number(p.totalValueMinor),String(p.currency))}`:`单位净值 ${Number(p.unitValueHundredMillionths??Number(p.unitValueTenThousandths)*10000)/1e8} ${String(p.currency)}`} {b?` · 基准 ${b.quantityMicro/1e6} 份 · 版本 ${b.revision}`:''}</p>}{p.unitPriceHundredMillionths!=null&&<p>参考单价 {Number(p.unitPriceHundredMillionths)/1e8} {String(p.currency)}（不用于成本计算）</p>}{Boolean(p.linkedTransferId)&&<p>关联已有转入 {String(p.linkedTransferId)}；本次不再转入扣款。</p>}{f&&<p>两步一起生效，任何一步失败均回滚。转入不是新增投入或消费。</p>}</div>;}
export function InvestmentMetadataModal({investment,householdId,close,refresh,notify,readOnly=false}:{investment?:Row;householdId:string;close:()=>void;refresh:()=>void;notify:(s:string)=>void;readOnly?:boolean}) {
 const [name,setName]=useState(String(investment?.name??'')),[ticker,setTicker]=useState(String(investment?.ticker??'')),[assetType,setAssetType]=useState(String(investment?.asset_type??'基金 / ETF')),[currency,setCurrency]=useState(String(investment?.currency??'USD')),[unitName,setUnitName]=useState(String(investment?.unit_name??'份')),[note,setNote]=useState(String(investment?.note??'')),[cadence,setCadence]=useState(String(investment?.valuation_cadence??'weekly')),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(readOnly)return notify('只读预览，不保存标的信息。');setBusy(true);setError('');try{const payload={name,ticker,assetType,unitName,note,valuationCadence:cadence,...(!investment?{householdId,currency}:{})},r=await fetch(investment?`/api/investments/${investment.id}`:'/api/investments',{method:investment?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),b=await r.json();if(!r.ok)throw new Error(b.error??'保存失败');close();notify(investment?'标的信息已更新':'已创建零持仓标的，请在对应卡片发起投资操作。');refresh();}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 return <Shell title={investment?'编辑投资标的':'新增投资标的'} close={close}><form onSubmit={submit} className="space-y-3"><p className="text-xs text-gray-500">新标的初始份额和成本固定为 0；持仓只从已批准交易计算。币种创建后固定。</p><label className="block text-sm">标的名称<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">代码（可选）<input maxLength={30} value={ticker} onChange={e=>setTicker(e.target.value)}/></label><label className="block text-sm">资产类型<input list="asset-types" required maxLength={40} value={assetType} onChange={e=>setAssetType(e.target.value)}/><datalist id="asset-types">{['基金 / ETF','股票','债券','其他'].map(t=><option key={t}>{t}</option>)}</datalist></label><label className="block text-sm">币种<select disabled={Boolean(investment)} value={currency} onChange={e=>setCurrency(e.target.value)}>{['USD','CNY','HKD'].map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm">份额单位<input required maxLength={20} value={unitName} onChange={e=>setUnitName(e.target.value)}/></label><label className="block text-sm">估值提醒<select value={cadence} onChange={e=>setCadence(e.target.value)}><option value="weekly">每周</option><option value="monthly">每月</option></select></label><label className="block text-sm">备注<textarea maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-[#1f5243] py-3 font-bold text-white">{busy?'保存中…':'保存标的'}</button></form></Shell>;
}
